### PR TITLE
Fixed _calc_dihedral and Dihedral.dihedrals

### LINKED ISSUE #1554: u.dihedrals.dihedrals() returns negative angles as positive
### Expected behaviour
u.dihedrals.dihedrals() to return the angles in radians.

### Actual behaviour
u.dihedrals.dihedrals() returns the angles in radians, but all the negative angles are positive.

### Note
u.dihedrals._dihedralsSlow() works, so the problem should be in the Cython implementation.

### Code to reproduce the behaviour

``` python
In [1]: import MDAnalysis as mda
        from MDAnalysis.core.topologyattrs import Angles, Dihedrals
        from MDAnalysis.topology.guessers import guess_angles, guess_dihedrals

In [2]: u = mda.Universe('example.pdb', 'example.trr')

In [3]: angles_list = Angles(guess_angles(u.bonds), guessed=True)
        u.add_TopologyAttr(angles_list)
        dihedrals_list = Dihedrals(guess_dihedrals(u.angles), guessed=True)
        u.add_TopologyAttr(dihedrals_list)

In [4]: u.dihedrals.dihedrals()[:10], u.dihedrals._dihedralsSlow()[:10]
Out[4]: (array([ 3.02015785,  0.0497024 ,  1.87342152,  1.09379527,  1.59478878,
                 2.97920885,  1.02250218,  2.65210548,  0.44485898,  1.89326366]),
         array([ 3.02015829, -0.04970198,  1.87342155, -1.09379518,  1.59478879,
                 2.97920895, -1.02250218,  2.65210557, -0.44485903,  1.89326358], dtype=float32))

```

### Currently version of MDAnalysis:
0.16.2

### PR DESCRIPTION
**Pull request by nestorwendt**
Closes #1554 and #1565
-
Changes made in this Pull Request:
 -
### #1554:
Fixed *y* calculation in calc_distances.h _calc_dihedral* following this equation:

Dihedral formula

To reduce redundancy in the C code I created a new function that receives three vectors as input and returns the angle.

### #1565:
While discussing #1554 with @mnmelo, we discovered that _calc_dihedral* and Dihedrals.dihedrals() calculate the inverse vectors (ba, cb, dc) instead of (ab, bc, cd). This results in this methods returning the inverse angle. Dihedral.value() is fine (follows the [IUPAC convention](https://goldbook.iupac.org/html/T/T06406.html)), so I changed the formers to follow the IUPAC convention as well.

### Tests:
Tests were modified to fit the changes. There are 4 tests failing. This is intentional and happens because when the dihedral angle is 180° the C code returns *0.0* and the numpy/.value() methods return *nan*. The tests expect the dihedral angle to be *nan*. Should we strive for consistency between methods?

PR Checklist
------------
 - [X] Tests?
 - [ ] Docs?
 - [X] CHANGELOG updated?
 - [X] Issue raised/referenced?

### CODE REVIEW

**Comment by mnmelo** [comment]
The `nan` vs. `0.0` problem arises not when the dihedral is 180º but when the constructing atoms are colinear (when the abc or bcd _angles_ are 180º).

**Comment by mnmelo** [comment]
Ah, and maybe it's clearer if I disclose that Nestor (@nestorwendt) is a student here at my lab now :)

File: package/CHANGELOG [hunk 1]
```diff
@@ -14,7 +14,7 @@ The rules for this file:
 
 ------------------------------------------------------------------------------
 mm/dd/17 richardjgowers, rathann, orbeckst, tylerjereddy, mtiberti, kain88-de,
-         jbarnoud
+         jbarnoud, nestorwendt
```
Comment (kain88-de) [inline package/CHANGELOG]: Please also add yourself to the authors file

File: package/MDAnalysis/lib/include/calc_distances.h [hunk 2]
```diff
@@ -531,54 +531,62 @@ static void _calc_angle_triclinic(coordinate* atom1, coordinate* atom2,
...
+  n2[2] =-vb[0]*vc[1] + vb[1]*vc[0];
+
+  // x = dot(n1,n2) = cos theta
+  x = (n1[0]*n2[0] + n1[1]*n2[1] + n1[2]*n2[2]);
+
+  xp[0] = n1[1]*n2[2] - n1[2]*n2[1];
+  xp[1] =-n1[0]*n2[2] + n1[2]*n2[0];
+  xp[2] = n1[0]*n2[1] - n1[1]*n2[0];
+
+  y = (xp[0]*vb[0] + xp[1]*vb[1] + xp[2]*vb[2]) / \
```
Comment (kain88-de) [inline package/MDAnalysis/lib/include/calc_distances.h]: please avoid line continuation characters `\` in new code.

File: package/MDAnalysis/lib/include/calc_distances.h [hunk 3]
```diff
@@ -531,54 +531,62 @@ static void _calc_angle_triclinic(coordinate* atom1, coordinate* atom2,
...
+    vb[0] = atom2[i][0] - atom3[i][0];
+    vb[1] = atom2[i][1] - atom3[i][1];
+    vb[2] = atom2[i][2] - atom3[i][2];
 
-    *(angles + i) = atan2(y,x); //atan2 is better conditioned than acos
+    vc[0] = atom3[i][0] - atom4[i][0];
+    vc[1] = atom3[i][1] - atom4[i][1];
+    vc[2] = atom3[i][2] - atom4[i][2];
+
+    *(angles + i) = _calc_dihedral_angle(va, vb, vc); //atan2 is better conditioned than acos
```
Comment (kain88-de) [inline package/MDAnalysis/lib/include/calc_distances.h]: I think the comment can go

File: package/MDAnalysis/lib/include/calc_distances.h [hunk 4]
```diff
@@ -588,56 +596,33 @@ static void _calc_dihedral_ortho(coordinate* atom1, coordinate* atom2,
...
-    // tan theta = y/x
-    x = (n1[0]*n2[0] + n1[1]*n2[1] + n1[2]*n2[2]);
-
-    xp[0] = n1[1]*n2[2] - n1[2]*n2[1];
-    xp[1] =-n1[0]*n2[2] + n1[2]*n2[0];
-    xp[2] = n1[0]*n2[1] - n1[1]*n2[0];
-    y = sqrt(xp[0]*xp[0] + xp[1]*xp[1] + xp[2]*xp[2]);
-
-    *(angles + i) = atan2(y,x); //atan2 is better conditioned than acos
+    *(angles + i) = _calc_dihedral_angle(va, vb, vc); //atan2 is better conditioned than acos
```
Comment (kain88-de) [inline package/MDAnalysis/lib/include/calc_distances.h]: the comment here can go

File: package/MDAnalysis/lib/include/calc_distances.h [hunk 5]
```diff
@@ -666,46 +648,26 @@ static void _calc_dihedral_triclinic(coordinate* atom1, coordinate* atom2,
...
```
Comment (kain88-de) [inline package/MDAnalysis/lib/include/calc_distances.h]: the comment can go

**Comment by nestorwendt** [comment]
After more thought, it seems that Dihedral.value() is the implementation outside the convention. Here's a good test:

```
def wiki_dihedral(a, b, c, d): #https://en.wikipedia.org/wiki/Dihedral_angle
    ab = a-b
    bc = b-c
    cd = c-d

    n1 = np.cross(ab, bc)
    n2 = np.cross(bc, cd)

    x = np.dot(n1, n2)
    
    xp = np.cross(n1, n2)
    norm_vb = np.linalg.norm(bc)
    
    y = np.dot(xp, bc) / norm_vb
    
    return np.arctan2(y, x)

# Correct implementation, angle should be 90.0
import numpy as np

a = np.array([0, 0, 0])
b = np.array([-1, 0, 0])
c = np.array([-1, 0, -1])
d = np.array([-1, 1, -1])

print(np.rad2deg(wiki_dihedral(a, b, c, d)))

# mdamath implementation (Dihedral.value() and Dihedrals.dihedrals())
from MDAnalysis.lib.mdamath import dihedral

ab = a-b
bc = b-c
cd = c-d

print(np.rad2deg(dihedral(ab, bc, cd)))
```

So this is how we stand:

**In the current version:**
* Dihedral.value() returns the inverse angle.
* Dihedrals.dihedrals() returns the correct angles.
* _calc_dihedral* (cython) returns the correct positive angles, but inverted negative angles.

**After the changes in this PR:**

* All methods return the inverse angle (or correct angle in a left-handed Cartesian coordinate system).

Setting all implementations to return dihedral angle in the right-handed coordinate system break ~20 tests. They all have hard-coded dihedral angle values. So, two things need to be decided:

1. How to handle the `nan` vs `0.0` situation. Should I add a if statement in the C code to make it consistent with the numpy implementation?
1. Should I set all implementations to the right-handed coordinate system and modify the hard-coded tests?

**Comment by kain88-de** [comment]
Yes all angles should be right handed coordinate systems. This means we need to change tests then I'm ok with it.

About Nan. It would be nice to be consistent with numpy.

**Comment by nestorwendt** [comment]
Everything should be in the convention now and the C code is consistent with numpy. While changing the tests I found another bug (#1572). The modulo use in eaf1a4b is performance-wise equal to using if/elses but is cleaner.

File: package/MDAnalysis/lib/include/calc_distances.h [hunk 6]
```diff
@@ -531,54 +531,67 @@ static void _calc_angle_triclinic(coordinate* atom1, coordinate* atom2,
   }
 }
 
+static double _calc_dihedral_angle(double* va, double* vb, double* vc)
```
Comment (mnmelo) [inline package/MDAnalysis/lib/include/calc_distances.h]: I think there might be a minor gain in performance if this function already takes the pointer to the result array slot, and write directly there instead of returning a double.

**Comment by richardjgowers** [comment]
@nestorwendt I'm a little confused, but it's been a while since I wrote this code.  The vector `A->B` (from A to B) is made by doing `O->B - O->A`, where `O` is the origin.  So in the `wiki_dihedral` function above, it should be `ab = b - a`

**Comment by nestorwendt** [comment]
@richardjgowers Yes, and then you can return just the atan2(y, x) instead of -atan2(y, x).

**Comment by nestorwendt** [comment]
**Hopefully** everything is right now. The angles are also equal to those calculated with Pymol.

**Comment by mnmelo** [comment]
This is erroring out because of anaconda channel failures. I'm restarting the builf to check if it was just a connectivity hiccup, but maybe something needs adjusting now that travis changed the default to [ubuntu trusty](https://goo.gl/Qp1wuP).

**Comment by mnmelo** [comment]
Ok, it seems the problem is upstream in [astropy/ci-helpers](https://github.com/astropy/ci-helpers), which is not passing a travis build itself. Perhaps also a consequence of the travis ubuntu update.

@kain88-de, you have more experience with this: is there anything we can do other than wait for astropy to fix it themselves?

**Comment by kain88-de** [comment]
See https://github.com/Anaconda-Platform/support/issues/126

There is a general problem on anaconda right now.

**Comment by mnmelo** [comment]
Bummer... Let's wait, then...

**Comment by kain88-de** [comment]
Should be fixed now. I restarted the build.

**Comment by mnmelo** [comment]
The python 3.4 build timed out. Restarted it.

**Comment by mnmelo** [comment]
There's something fishy with the 3.4 build. It's already over 30 min and is still at the preparation step.

**Comment by kain88-de** [comment]
Yeah it can't find the correct numpy version. This means it sometimes takes longer but this is still a bit to long.

**Comment by mnmelo** [comment]
Ah, github isn't clever enough to understand when a commit closes multiple issues like we wrote this one. #1554 was closed automatically; I closed #1565 and #1572 by hand.

**Comment by mnmelo** [comment]
And thanks, @nestorwendt, for your first merged PR (hopefully of many!)

**Comment by orbeckst** [comment]
@nestorwendt congratulations to your first merged PR, welcome to the community.

I am also sending you an invite as a contributor to MDAnalysis.
