### PR TITLE
Switch to scientifc python nightly package location for cron tests against upstream nightly wheels

### LINKED ISSUE #4202: Cron job pointing to wrong nightly builds location
We're using the old scipy conda repo rather than scientific python. We should switch over.

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #4202 

Changes made in this Pull Request:
 - switch target for nightly wheel repo
 - remove h5py from list (hasn't been updated in a long while in nightly builds anyways)
 - Switch deprecated PyArray_DOUBLE to NPY_DOUBLE in transformations code

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

----
:books: Documentation preview :books:: https://mdanalysis--4203.org.readthedocs.build/en/4203/

### CODE REVIEW

File: package/MDAnalysis/lib/src/transformations/transformations.c [hunk 1]
```diff
@@ -786,7 +786,7 @@ PyConverter_AnyDoubleArray(
     PyObject **address)
 {
     PyArrayObject *obj = (PyArrayObject *)object;
-    if (PyArray_Check(object) && obj->descr->type_num == PyArray_DOUBLE) {
+    if (PyArray_Check(object) && obj->descr->type_num == NPY_DOUBLE) {
```
Comment (IAlibay) [inline package/MDAnalysis/lib/src/transformations/transformations.c:789]: @hmacdope or @richardjgowers - am I correct in thinking that this is an acceptable replacement for the now removed PyArray_DOUBLE?

File: .github/workflows/gh-ci-cron.yaml [hunk 2]
```diff
@@ -3,6 +3,9 @@ on:
   schedule:
     # 3 am Tuesdays and Fridays
     - cron: "0 3 * * 2,5"
+  pull_request:
```
Comment (IAlibay) [inline .github/workflows/gh-ci-cron.yaml]: TODO: remove before merge

**Comment by IAlibay** [comment]
We can't say if we're fully compatible with the current numpy 2.0-dev until #4198 is merged, but at least this gets us back to properly testing against nightly upstream.

**Comment by IAlibay** [comment]
pinging @MDAnalysis/coredevs - would be great to get our cron checks working again

**Comment by IAlibay** [comment]
This is stalling us from going green on CRON CI - I'm going to reask for a review @MDAnalysis/coredevs

File: package/MDAnalysis/lib/src/transformations/transformations.c (hunk 1 above)
Comment (tylerjereddy) [reply package/MDAnalysis/lib/src/transformations/transformations.c:789]: Looks correct to me, there is even a `tools/replace_old_macros.sed` in the NumPy repo that does what you did.

**Review by tylerjereddy — APPROVED** [review]
CI is green, +1 for merge after backing out the `yaml` shim to flush here

**Comment by IAlibay** [comment]
Thanks @tylerjereddy !
